#!/usr/bin/env python3
"""Enforce: namespace == assembly name + folder path.

The template previously carried four competing namespace schemes for the same
kind of file, which left no rule to infer when adding a feature. One rule now
holds, and this keeps it that way.

Exit code 1 on any mismatch, so it can gate CI.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Generated by tooling; their layout is not ours to dictate.
SKIP_PARTS = {"obj", "bin", "node_modules", "Migrations"}

NAMESPACE_RE = re.compile(r"^\s*namespace\s+([\w.]+)", re.MULTILINE)


def expected_namespace(assembly: str, source: Path, project_root: Path) -> str:
    folders = source.relative_to(project_root).parent.parts
    return ".".join((assembly, *folders)) if folders else assembly


def main() -> int:
    violations: list[str] = []
    checked = 0

    for csproj in sorted((REPO_ROOT / "src").rglob("*.csproj")):
        project_root, assembly = csproj.parent, csproj.stem

        for source in sorted(project_root.rglob("*.cs")):
            if SKIP_PARTS & set(source.relative_to(project_root).parts):
                continue

            match = NAMESPACE_RE.search(source.read_text(encoding="utf-8"))
            if not match:
                continue

            checked += 1
            actual = match.group(1)
            expected = expected_namespace(assembly, source, project_root)
            if actual != expected:
                violations.append(
                    f"{source.relative_to(REPO_ROOT)}\n"
                    f"    found:    {actual}\n"
                    f"    expected: {expected}"
                )

    if violations:
        print(f"{len(violations)} namespace violation(s):\n", file=sys.stderr)
        for violation in violations:
            print(f"  {violation}\n", file=sys.stderr)
        print(
            "Rule: namespace == assembly name + folder path.\n"
            "Either move the file or rename the namespace - see CLAUDE.md.",
            file=sys.stderr,
        )
        return 1

    print(f"OK - {checked} files follow: namespace == assembly name + folder path")
    return 0


if __name__ == "__main__":
    sys.exit(main())
